language: ruby
rvm:
  - 2.5.3

services:
  - docker

before_install:
  - docker build -f container-images/local-dev/Dockerfile -t uncontained-local-dev .

script:
  - docker run -u $(id -u) -v ${PWD}:/uncontained.io:Z -it uncontained-local-dev test
